# @package _global_

defaults:
  - _self_
  - data: intentonomy # choose datamodule with `test_dataloader()` for evaluation
  - model: intentonomy_resnet101_mcc
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["intentonomy", "resnet101", "mcc"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
